# .woodpecker.yml
when:
  branch: [main, dev]

steps:
  setup:
    image: alpine

    commands:
      - sh setup.sh
  
  test:
    image: alpine

    commands:
      - apk add --no-cache openssl
      - sh test.sh
